export const ROUTES = {
  ACCORDION: "/accordion/",
  AVATAR: "/avatar/",
  BUTTON: "/button/",
  CHECKBOX: "/checkbox/",
  DOCUMENT_VIEWER: "/document-viewer",
  FORM: "/form/",
  HAMBURGER: "/hamburger/",
  ICON: "/icon/",
  ICON_BUTTON: "/icon-button/",
  MODAL: "/modal/",
  HOME: "/",
  OVERLAY: "/overlay/",
  PAGINATION: "/pagination",
  RATING: "/rating",
  SCROLLBAR: "/scrollbar/",
  SELECT: "/select/",
  SIDEBAR: "/sidebar/",
  SPINNER: "/spinner/",
  TABS: "/tabs",
  TEXTAREA: "/textarea/",
  UPLOADER: "/uploader/",
};
