export enum ActionTypes {
  LOGOUT_REQUEST = "account/LOGOUT_REQUEST",
  LOGOUT_SUCCESS = "account/LOGOUT_SUCCESS",
  LOGOUT_FAILED = "account/LOGOUT_FAILED",
  TOKEN_REQUEST = "account/TOKEN_REQUEST",
  TOKEN_SUCCESS = "account/TOKEN_SUCCESS",
  TOKEN_FAILED = "account/TOKEN_FAILED",
}
