# Generated by Django 3.2.7 on 2021-11-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=999)),
                ('file', models.FileField(default='', upload_to='files')),
                ('encodedData', models.TextField()),
            ],
        ),
    ]
